version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: sample_user
      POSTGRES_PASSWORD: sample_pass
      POSTGRES_DB: sample_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
